method: 'CM_DAELSTM'
train: True
dataset: 'cfo'
mod_type: ["BPSK", "QPSK", "8PSK", "PAM4", "QAM16", "QAM32", "QAM64", "QAM128", "QAM256", "GFSK", "WBFM", "AM-DSB", "AM-SSB", "OOK", "4ASK", "8ASK", "16PSK", "32PSK","8APSK","GMSK", "DQPSK","16APSK","32APSK","64APSK","128APSK"]
workers: 8
seed: 2019
gpu: 0
cpu: False
params:
    "network": 'CM_DAELSTM'
    "loss": 'loss_CE_and_MSE'
    "batch_size": 128
    "epochs": 200
    "lr": 1e-3
    "lr_decay": 0.
    "weight_decay": 0.
    "early_stop": False
    "Xmode": [{"type":"AP","options":{"IQ_norm":False, "zero_mask":True}}]






















