method: 'ours'
train: True
dataset: 'cfo'
mod_type: ["BPSK", "QPSK", "8PSK", "PAM4", "QAM16", "QAM32", "QAM64", "QAM128", "QAM256", "GFSK", "WBFM", "AM-DSB", "AM-SSB", "OOK", "4ASK", "8ASK", "16PSK", "32PSK","8APSK","GMSK", "DQPSK","16APSK","32APSK","64APSK","128APSK"]
workers: 8
seed: 1
gpu: 0
cpu: False
params:
    "network": "TransGroupNet"
    "loss": "loss_CE"
    "batch_size": 1024
    "epochs": 200
    "lr": 5e-3
    "lr_decay": 0.8
    "weight_decay": 5e-2
    "early_stop": False
    "Xmode": [{"type":"APF_ours","options":{"IQ_norm":False, "zero_mask":False}}]






